"""Bounded MCP interoperability contracts for OpsLens."""

from opslens.mcp_boundary.adapters import (
    InMemoryMcpInvocationResolver,
    build_offline_mcp_execution_server,
    build_offline_mcp_server,
    build_offline_mcp_structured_result_server,
)
from opslens.mcp_boundary.application import (
    McpAdmissionProjection,
    McpExecutionOutcome,
    McpExecutionProjection,
    admit_mcp_invocation_reference,
    admit_mcp_tool_call,
    execute_mcp_invocation_reference,
    execute_mcp_invocation_reference_outcome,
    project_mcp_structured_result_reference,
    resolve_mcp_invocation_reference,
)
from opslens.mcp_boundary.domain import (
    MAX_MCP_EPSS_TEXT_CHARS,
    MAX_MCP_RESULT_ROWS,
    MCP_CAPABILITY_EXECUTION_CONTRACT_VERSION,
    MCP_CAPABILITY_EXPOSURE_CONTRACT_VERSION,
    MCP_RESULT_PROJECTION_CONTRACT_VERSION,
    McpBoundaryValidationError,
    McpCapabilityExecutionBridge,
    McpCapabilityExposure,
    McpInvocationReference,
    McpStructuredEpssRow,
    McpStructuredSecurityResultProjection,
    McpToolCallAdmission,
    McpToolName,
    capability_for_mcp_tool,
    list_mcp_capability_exposures,
    mcp_tool_for_capability,
    parse_mcp_tool_name,
)
from opslens.mcp_boundary.ports import McpInvocationResolver

__all__ = [
    "MAX_MCP_EPSS_TEXT_CHARS",
    "MAX_MCP_RESULT_ROWS",
    "MCP_CAPABILITY_EXECUTION_CONTRACT_VERSION",
    "MCP_CAPABILITY_EXPOSURE_CONTRACT_VERSION",
    "MCP_RESULT_PROJECTION_CONTRACT_VERSION",
    "InMemoryMcpInvocationResolver",
    "McpAdmissionProjection",
    "McpBoundaryValidationError",
    "McpCapabilityExecutionBridge",
    "McpCapabilityExposure",
    "McpExecutionOutcome",
    "McpExecutionProjection",
    "McpInvocationReference",
    "McpInvocationResolver",
    "McpStructuredEpssRow",
    "McpStructuredSecurityResultProjection",
    "McpToolCallAdmission",
    "McpToolName",
    "admit_mcp_invocation_reference",
    "admit_mcp_tool_call",
    "build_offline_mcp_execution_server",
    "build_offline_mcp_server",
    "build_offline_mcp_structured_result_server",
    "capability_for_mcp_tool",
    "execute_mcp_invocation_reference",
    "execute_mcp_invocation_reference_outcome",
    "list_mcp_capability_exposures",
    "mcp_tool_for_capability",
    "parse_mcp_tool_name",
    "project_mcp_structured_result_reference",
    "resolve_mcp_invocation_reference",
]
