"""Domain types for immutable repository intelligence evidence."""

from opslens.repository_intelligence.domain.errors import (
    InvalidGitHubSourceEvidenceError,
    InvalidRepositoryFileEvidenceError,
    InvalidRepositoryIdentityError,
    InvalidRepositoryNvdEnrichmentError,
    InvalidRepositorySnapshotError,
    InvalidRepositoryVulnerabilityScanError,
    InvalidUvLockError,
    RepositoryIntelligenceContractError,
    RepositoryNvdEnrichmentLimitError,
    RepositoryVulnerabilityScanLimitError,
    UnsupportedRepositoryFileError,
    UnsupportedRepositoryVisibilityError,
    UnsupportedUvLockSchemaError,
)
from opslens.repository_intelligence.domain.file_evidence import (
    MAX_REPOSITORY_FILE_BYTES,
    UV_LOCK_PATH,
    ImmutableRepositoryFileEvidence,
    compute_content_sha256,
    compute_git_blob_sha1,
    validate_repository_evidence_path,
)
from opslens.repository_intelligence.domain.models import (
    GitHubRepositoryIdentity,
    ImmutableRepositorySnapshot,
    RepositoryProvider,
    validate_github_repository_coordinates,
    validate_github_repository_ref,
)
from opslens.repository_intelligence.domain.nvd_enrichment import (
    MAX_NVD_ENRICHMENT_RECORDS,
    RepositoryNvdCvssEvidence,
    RepositoryNvdEnrichedFinding,
    RepositoryNvdEnrichmentEvidence,
    derive_repository_nvd_cvss_evidence,
)
from opslens.repository_intelligence.domain.pypi_normalization import (
    NormalizedRepositoryPyPIDependencyEvidence,
    RepositoryPyPINormalizationInventory,
    UnsupportedRepositoryPyPINormalizationEvidence,
)
from opslens.repository_intelligence.domain.uv_lock import (
    MAX_UV_LOCK_PACKAGE_RECORDS,
    PYPI_SIMPLE_REGISTRY_URL,
    SUPPORTED_UV_LOCK_REVISIONS,
    SUPPORTED_UV_LOCK_SCHEMA_VERSION,
    ParsedUvLockEvidence,
    UvLockedPyPIPackageEvidence,
    UvUnsupportedLockedPackageEvidence,
    UvUnsupportedPackageReason,
)
from opslens.repository_intelligence.domain.vulnerability_findings import (
    MAX_GHSA_VULNERABILITY_OCCURRENCES,
    MAX_REPOSITORY_VULNERABILITY_CANDIDATE_EVALUATIONS,
    RepositoryPyPIVulnerabilityAssessment,
    RepositoryPyPIVulnerabilityFinding,
    RepositoryVulnerabilityScanEvidence,
    UnsupportedRepositoryGhsaJoinEvidence,
    validate_repository_ghsa_occurrence_provenance,
)

__all__ = [
    "MAX_GHSA_VULNERABILITY_OCCURRENCES",
    "MAX_NVD_ENRICHMENT_RECORDS",
    "MAX_REPOSITORY_FILE_BYTES",
    "MAX_REPOSITORY_VULNERABILITY_CANDIDATE_EVALUATIONS",
    "MAX_UV_LOCK_PACKAGE_RECORDS",
    "PYPI_SIMPLE_REGISTRY_URL",
    "SUPPORTED_UV_LOCK_REVISIONS",
    "SUPPORTED_UV_LOCK_SCHEMA_VERSION",
    "UV_LOCK_PATH",
    "GitHubRepositoryIdentity",
    "ImmutableRepositoryFileEvidence",
    "ImmutableRepositorySnapshot",
    "InvalidGitHubSourceEvidenceError",
    "InvalidRepositoryFileEvidenceError",
    "InvalidRepositoryIdentityError",
    "InvalidRepositoryNvdEnrichmentError",
    "InvalidRepositorySnapshotError",
    "InvalidRepositoryVulnerabilityScanError",
    "InvalidUvLockError",
    "NormalizedRepositoryPyPIDependencyEvidence",
    "ParsedUvLockEvidence",
    "RepositoryIntelligenceContractError",
    "RepositoryNvdCvssEvidence",
    "RepositoryNvdEnrichedFinding",
    "RepositoryNvdEnrichmentEvidence",
    "RepositoryNvdEnrichmentLimitError",
    "RepositoryProvider",
    "RepositoryPyPINormalizationInventory",
    "RepositoryPyPIVulnerabilityAssessment",
    "RepositoryPyPIVulnerabilityFinding",
    "RepositoryVulnerabilityScanEvidence",
    "RepositoryVulnerabilityScanLimitError",
    "UnsupportedRepositoryFileError",
    "UnsupportedRepositoryGhsaJoinEvidence",
    "UnsupportedRepositoryPyPINormalizationEvidence",
    "UnsupportedRepositoryVisibilityError",
    "UnsupportedUvLockSchemaError",
    "UvLockedPyPIPackageEvidence",
    "UvUnsupportedLockedPackageEvidence",
    "UvUnsupportedPackageReason",
    "compute_content_sha256",
    "compute_git_blob_sha1",
    "derive_repository_nvd_cvss_evidence",
    "validate_github_repository_coordinates",
    "validate_github_repository_ref",
    "validate_repository_evidence_path",
    "validate_repository_ghsa_occurrence_provenance",
]